### ISSUE TITLE
Loading issues

### ISSUE THREAD

**Issue by BookZh** [city96/SD-Latent-Upscaler#5]
It shows successful loading in the console, but no related plugin node is found when using it in the browser interface.

**Comment by city96** [comment]
That seems odd. It should appear under the `latent` tab or by searching for it.

Latest ComfyUI?
Installed via git/manager/manually copied file?
Any browser console errors after reloading the UI (open dev tools, go to console and hit F5)?

![image](https://github.com/city96/SD-Latent-Upscaler/assets/125218114/ea16c0f4-5db1-45aa-859d-a9566b1ce6bb)

**Comment by BookZh** [comment]
Thanks for your reply, it could be a problem with my browser or the ComfyUI installer, I re-downloaded the latest installer and switched my browser to Google Chrome, I managed to find the Latent Upscaler node of SD-Latent-Upscaler according to the screenshot in your reply, Latant Interposar seems to be a new plugin, I found it on your homepage, I'll go install it and try it!

**Comment by city96** [comment]
Ah, sorry, though this issue was for the other repo at first since I recently updated that one lol. The upscaler should be right below it though.

Also, people usually prefer [this custom node](https://github.com/Ttl/ComfyUi_NNLatentUpscale) for latent upscaling, since it lets you select arbitrary scaling levels.

Good luck! Feel free to close the issue if it's resolved.

![image](https://github.com/city96/SD-Latent-Upscaler/assets/125218114/4f9de9c4-f9b0-4f03-8bd0-c56da34f0038)

**Comment by BookZh** [comment]
Haha, thanks again, both nodes were successfully loaded, I'm going to close this issue
